[provider]
cluster = "localnet"
wallet = "/Users/luca/.config/solana/id.json"

[test]
startup_wait = 10000

[test.validator]
url = "https://devnet.genesysgo.net/"

[[test.validator.clone]] # programID
address = "2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG"

[[test.validator.clone]] # idlAddress
address = "CKwZcshn4XDvhaWVH9EXnk3iu19t6t5xP2Sy2pD6TRDp"

[[test.validator.clone]] # programState
address = "BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt"

[[test.validator.clone]] # switchboardVault
address = "FVLfR6C2ckZhbSwBzZY4CX7YBcddUSge5BNeGQv5eKhy"

[[test.validator.clone]] # tokenWallet
address = "AKwZmswPBosB7YwgJPHTktLpG28nvN3UfL4CnMNhsBAX"

[[test.validator.clone]] # queue
address = "8zkZYWDWGwFzV64FF3HvK1LhtzYaMWgNBNs5iM5p7FWN"

[[test.validator.clone]] # queueAuthority
address = "6wb1NhACotpFH7geUTs2SBW7GTA8Zj6ANwB1TDc4JS6y"

[[test.validator.clone]] # queueBuffer
address = "HZQvBoB3AqtcqpnzGHpD8MPUvm8Ar2yXQPmsbEHMDb2Y"

[[test.validator.clone]] # crank
address = "G6QEcdU82KGeV4u5WvQ6ofHAb8cRHx4iZSyjE9jAS1zt"

[[test.validator.clone]] # crankBuffer
address = "2C8U9rYoGSj8g963J6wjaMfYAMUpYZ5Wiwiky3WHbKCj"

[[test.validator.clone]] # oracle
address = "9d5rbrY9H4zAknei1kywnfhoSN3nPutee47Zjb9Kmiuw"

[[test.validator.clone]] # oracleAuthority
address = "6wb1NhACotpFH7geUTs2SBW7GTA8Zj6ANwB1TDc4JS6y"

[[test.validator.clone]] # oracleEscrow
address = "9TGAKXUaCqoxJvyji538ascGZSdoiqBhryeL7Agmw9Y"

[[test.validator.clone]] # oraclePermissions
address = "4V21phQ9rmB6CBqpoKUdhZDiVKxUNsyvsKrkFWYZAer4"
