[features]
seeds = true
skip-lint = false
[programs.localnet]
dsla = "HaTDBm8Ps7P6xBWFq5YbRUAnSwvCZNTceTuMB2VC3azv"
[programs.devnet]
dsla = "HaTDBm8Ps7P6xBWFq5YbRUAnSwvCZNTceTuMB2VC3azv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
skip-deploy = true

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test.ts"
cli = "yarn run ts-mocha -p ./tsconfig.json cli/index.ts"
lint = "cargo dylint --all --workspace"

[workspace]
members = ["programs/dsla"]
types = "target/idl/"
