steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - stacktical-dsla-solana-uptime
      - --gen2
      - --runtime=nodejs16
      - --region=europe-west3
      - --source=.
      - --entry-point=monthlyUptime
      - --trigger-http
      - --allow-unauthenticated
      - --timeout=540s