name: Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  SOLANA_CLI_VERSION: 1.14.6
  NODE_VERSION: 18.12.0

jobs:
  test-core:
    name: Core Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup/
      - uses: ./.github/actions/setup-ts/
      - uses: ./.github/actions/setup-solana/
      - uses: actions/cache@v3
        name: Cache Cargo registry + index
        id: cache-cargo-build
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: cargo-${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}-0-0-1
      - run: yarn install
      - run: yarn lint
      - run: rustup default stable
      - run: cargo fmt -- --check
      # - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test
      - run: anchor run lint
      - run: anchor test
